export const Rules = {
  Program: 'Program',
  Assignment: 'Assignment',
  Each: 'Each',
  IfStatement: 'IfStatement',
  Pipe: 'Pipe',
  RelationExpression: 'RelationExpression',
  Expression: 'Expression',
  Term: 'Term',
  Factor: 'Factor',
  To: 'To',
  Function: 'Function',
  BrockStatement: 'BrockStatement',
  ToRight: 'ToRight',
  ToLeft: 'ToLeft',
  parenthesisExpression: 'parenthesisExpression',
  ReturnStatement: 'ReturnStatement',
};
