export const Rules = {
  Program: 'Program',
  Assignment: 'Assignment',
  Each: 'Each',
  IfStatement: 'IfStatement',
  PipeExpression: 'PipeExpression',
  RelationExpression: 'RelationExpression',
  Expression: 'Expression',
  Term: 'Term',
  Factor: 'Factor',
  To: 'To',
  Function: 'Function',
  BlockStatement: 'BlockStatement',
  ToRight: 'ToRight',
  ToLeft: 'ToLeft',
  ParenthesisExpression: 'ParenthesisExpression',
  ReturnStatement: 'ReturnStatement',
  PipeFrom: 'PipeFrom',
  PipeArguments: 'PipeArguments',
  LogicExpression: 'LogicExpression',
  RangeExpression: 'RangeExpression',
};
