export const Rules = {
  ProgramRoot: 'ProgramRoot' as const,
  Assignment: 'Assignment'  as const,
  Each: 'Each' as const,
  IfStatement: 'IfStatement' as const,
  PipeExpression: 'PipeExpression' as const,
  RelationExpression: 'RelationExpression' as const ,
  Expression: 'Expression' as const,
  Term: 'Term' as const,
  Factor: 'Factor' as const,
  To: 'To' as const,
  FunctionStatement: 'FunctionStatement' as const,
  BlockStatement: 'BlockStatement' as const,
  ToRight: 'ToRight' as const,
  ParenthesisExpression: 'ParenthesisExpression' as const,
  ReturnStatement: 'ReturnStatement' as const,
  PipeFrom: 'PipeFrom' as const,
  PipeArguments: 'PipeArguments' as const,
  LogicExpression: 'LogicExpression' as const,
  RangeExpression: 'RangeExpression' as const,
};
