name: Node Test

on:
  push:
    branches:
      - master
    paths:
        - 'packages/**'
  pull_request:
    paths:
      - 'packages/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [16, 18]

    steps:
      - name: Prepare / Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install
        run: |
          yarn install
      - name: yarn test
        run: |
          yarn run test
        env:
          CI: true